language: php

# list any PHP version you want to test against
matrix:
  include:
    - php: 5.6
      env: WITH_COVERAGE=true
    - php: 7.0  

# Commands to be run before your environment runs.
install: composer install

# Try if composer cache will speed up the build
#cache:
# directories:
#    - $HOME/.composer/cache/files

# omitting "script:" will default to phpunit
script: 
  - if [[ "$WITH_COVERAGE" == "true" ]];
    then vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml;
    else vendor/bin/phpunit --configuration tests/phpunit.xml;
    fi

after_script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter; fi
addons:
    code_climate:
        repo_token: 976417e6cf9bbe35142f2891a47bf42a93f0722b0390ff7dc790385c5a6c194f
