language: php

# list any PHP version you want to test against
php:
  - 5.4
  - 5.5
  - 5.6

# Commands to be run before your environment runs.
install: composer install --dev

# omitting "script:" will default to phpunit
script: phpunit --configuration tests/phpunit.xml

after_script:
  - vendor/bin/test-reporter
addons:
    code_climate:
        repo_token: 976417e6cf9bbe35142f2891a47bf42a93f0722b0390ff7dc790385c5a6c194f
