language: php

# list any PHP version you want to test against
php:
  - 5.4
  - 5.5
  - 5.6

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# omitting "script:" will default to phpunit
script: phpunit --configuration tests/phpunit.xml --coverage-text
